### ISSUE TITLE
Performance Evaluation

### ISSUE THREAD

**Issue by ptrdtznr** [iml130/bork#10]
How many "agents" can we handle? Is there a max value for it? Before doing the test implementation, a proper description of the test scenario is required

- [x] Description Test-Scenario
- [x] Jmeter Defintion
- [x] Execution 
- [x] Evaluation

**Comment by timpos** [comment]
Commit 97e28f3 fixed this by extending the documentation regarding the tests. The Apache JMeter test file was split into functional and load testing. An evaluation described by diagrams was added.
